[package]
name = "Akademia"
version = "0.0.1"
description = "Akademia Companion App"
authors = ["The Akademia Team"]
license = "Apache-2.0"
repository = "https://github.com/Akademiaapp/companion"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
devtools = "0.2.4"
tauri = { version = "1.5.3", features = ["devtools", "tracing"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = "1.0.193"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
